final List<Map<String, String>> generalQuestions = [
  {'this': 'Skydiving', 'that': 'SCUBA Diving'},
  {'this': 'Cable', 'that': 'Streaming'},
  {'this': 'Live Theater', 'that': 'Movie'},
  {'this': 'Sunrise Yoga', 'that': 'Sunset Meditation'},
  {'this': 'Sculpture Garden', 'that': 'Mural Wall'},
  {'this': 'Horseback Riding', 'that': 'Cycling'},
  {'this': 'Astronomy', 'that': 'Astrology'},
  {'this': 'Football', 'that': 'Basketball'},
  {'this': 'Leader', 'that': 'Follower'},
  {'this': 'Birdsong', 'that': 'Ocean Waves'},
  {'this': 'Streaming', 'that': 'YouTube'},
  {'this': 'New Clothes', 'that': 'New Phone'},
  {'this': 'Big Party', 'that': 'Small Gathering'},
  {'this': 'Sweater', 'that': 'Hoodie'},
  {'this': 'Fiction', 'that': 'Nonfiction'},
  {'this': 'Postcard', 'that': 'Souvenir'},
  {'this': 'Headphones', 'that': 'Speakers'},
  {'this': 'Save', 'that': 'Spend'},
  {'this': 'Stilettos', 'that': 'Ballet Flats'},
  {'this': 'Detective Novel', 'that': 'Fantasy Novel'},
  {'this': 'iOS', 'that': 'Android'},
  {'this': 'Flamenco', 'that': 'Tango'},
  {'this': 'TV Shows', 'that': 'Movies'},
  {'this': 'Meadow', 'that': 'Forest'},
  {'this': 'Film Photography', 'that': 'Digital Photography'},
  {'this': 'Train Ride', 'that': 'Bike Ride'},
  {'this': 'Ice Sculpture', 'that': 'Sand Sculpture'},
  {'this': 'Acoustic Guitar', 'that': 'Electric Guitar'},
  {'this': 'Sing', 'that': 'Dance'},
  {'this': 'Couch', 'that': 'Recliner'},
  {'this': 'Coffee Cup', 'that': 'Thermos'},
  {'this': 'Highway', 'that': 'Rural Road'},
  {'this': 'Lemonade Stand', 'that': 'Coffee Shop'},
  {'this': 'Folk Tales', 'that': 'Science Fiction'},
  {'this': 'Skydiving', 'that': 'Paragliding'},
  {'this': 'Sketching', 'that': 'Painting'},
  {'this': 'Campfire', 'that': 'Fireplace'},
  {'this': 'Bicycle', 'that': 'Skateboard'},
  {'this': 'Acoustic Music', 'that': 'Electronic Music'},
  {'this': 'Vinyl Records', 'that': 'Streaming Music'},
  {'this': 'Individual Sports', 'that': 'Team Sports'},
  {'this': 'Road Trip', 'that': 'Plane Trip'},
  {'this': 'Roller Derby', 'that': 'Figure Skating'},
  {'this': 'Amusement Park', 'that': 'Day at the Beach'},
  {'this': 'Drawing', 'that': 'Sculpting'},
  {'this': 'Money', 'that': 'Free Time'},
  {'this': 'Freelancer', 'that': 'Employee'},
  {'this': 'Used Bookstore', 'that': 'Brand-New Bookstore'},
  {'this': 'Text', 'that': 'Call'},
  {'this': 'Ocean', 'that': 'Mountains'},
  {'this': 'Marathon', 'that': 'Triathlon'},
  {'this': 'Roller Coaster', 'that': 'Ferris Wheel'},
  {'this': 'Honesty', 'that': 'Other’s Feelings'},
  {'this': 'Historical Tour', 'that': 'Nature Hike'},
  {'this': 'Swimming', 'that': 'Sunbathing'},
  {'this': 'Sunflower', 'that': 'Rose'},
  {'this': 'Laundry', 'that': 'Dishes'},
  {'this': 'Thrift Store', 'that': 'Retail Store'},
  {'this': 'Mac', 'that': 'PC'},
  {'this': 'Art Museum', 'that': 'Natural History Museum'},
  {'this': 'Aquarium', 'that': 'Aviary'},
  {'this': 'Wizard / Witches', 'that': 'Superheroes'},
  {'this': 'Right Side Up', 'that': 'Upside Down'},
  {'this': 'Train', 'that': 'Plane'},
  {'this': 'Online Gaming', 'that': 'Traditional Board Games'},
  {'this': 'Formal', 'that': 'Casual'},
  {'this': 'Mystery Novel', 'that': 'Sci-Fi Novel'},
  {'this': 'Waltz', 'that': 'Salsa'},
  {'this': 'City Skyline', 'that': 'Mountain Range'},
  {'this': 'Puppet Show', 'that': 'Magic Show'},
  {'this': 'Polka Dots', 'that': 'Stripes'},
  {'this': 'Sandalwood Scent', 'that': 'Vanilla Scent'},
  {'this': 'Folk', 'that': 'Hip Hop'},
  {'this': 'Card Game', 'that': 'Board Game'},
  {'this': 'Hardcover', 'that': 'Paperback'},
  {'this': 'Iced Coffee', 'that': 'Hot Coffee'},
  {'this': 'Console Gaming', 'that': 'PC Gaming'},
  {'this': 'Glasses', 'that': 'Contacts'},
  {'this': 'City', 'that': 'Countryside'},
  {'this': 'Cactus', 'that': 'Succulent'},
  {'this': 'Water Rafting', 'that': 'Kayaking'},
  {'this': 'Gas Car', 'that': 'Electric Car'},
  {'this': 'Winter Solstice', 'that': 'Summer Solstice'},
  {'this': 'Traditional Art', 'that': 'Digital Art'},
  {'this': 'Social Butterfly', 'that': 'Lone Wolf'},
  {'this': 'Roller Skates', 'that': 'Ice Skates'},
  {'this': 'Cash', 'that': 'Credit'},
  {'this': 'Canoe', 'that': 'Kayak'},
  {'this': 'City Marathon', 'that': 'Trail Run'},
  {'this': 'Hammock', 'that': 'Lawn Chair'},
  {'this': 'Natural Pool', 'that': 'Man-Made Pool'},
  {'this': 'Thrift Store Finds', 'that': 'High-End Purchases'},
  {'this': 'Fishing', 'that': 'Hunting'},
  {'this': 'Rain', 'that': 'Snow'},
  {'this': 'Yoga', 'that': 'Weightlifting'},
  {'this': 'Football', 'that': 'Soccer'},
  {'this': 'Marathon', 'that': 'Sprint'},
  {'this': 'Music', 'that': 'Podcasts'},
  {'this': 'E-Bike', 'that': 'Traditional Bicycle'},
  {'this': 'Movie at Home', 'that': 'Movie at the Theater'},
  {'this': 'Kite Flying', 'that': 'Frisbee Throwing'},
  {'this': 'Second-Hand Book', 'that': 'New Book'},
  {'this': 'Bonsai Tree', 'that': 'Oak Tree'},
  {'this': 'Morning Person', 'that': 'Night Owl'},
  {'this': 'Cardio', 'that': 'Weights'},
  {'this': 'Vertical Stripes', 'that': 'Horizontal Stripes'},
  {'this': 'High-tech', 'that': 'Low-tech'},
  {'this': 'Email', 'that': 'Letter'},
  {'this': 'Tablet', 'that': 'Computer'},
  {'this': 'Pop', 'that': 'Indie'},
  {'this': 'Ninjas', 'that': 'Pirates'},
  {'this': 'Jungle', 'that': 'Desert'},
  {'this': 'Public School', 'that': 'Home School'},
  {'this': 'Mountain Climbing', 'that': 'Cave Diving'},
  {'this': 'Motorcycle', 'that': 'Bicycle'},
  {'this': 'Passenger', 'that': 'Driver'},
  {'this': 'TV', 'that': 'Book'},
  {'this': 'Bubble Bath', 'that': 'Mud Bath'},
  {'this': 'Audiobook', 'that': 'Podcast'},
  {'this': 'Dog', 'that': 'Cat'},
  {'this': 'Canoeing', 'that': 'Rafting'},
  {'this': 'Drum Circle', 'that': 'Choir'},
  {'this': 'Form', 'that': 'Function'},
  {'this': 'Online Shopping', 'that': 'Shopping in a Store'},
  {'this': 'Intelligent', 'that': 'Funny'},
  {'this': 'Botanical Garden', 'that': 'Zoo'},
  {'this': 'Introvert', 'that': 'Extrovert'},
  {'this': 'Rock Garden', 'that': 'Flower Garden'},
  {'this': 'Trampoline', 'that': 'Bouncy Castle'}
];

final List<Map<String, String>> foodQuestions = [
  {'this': 'Sweet', 'that': 'Savory'},
  {'this': 'Garden Salad', 'that': 'Caesar Salad'},
  {'this': 'Pineapples', 'that': 'Coconuts'},
  {'this': 'Hot Chocolate', 'that': 'Iced Tea'},
  {'this': 'Vegan Diet', 'that': 'Carnivorous Diet'},
  {'this': 'Broccoli', 'that': 'Cauliflower'},
  {'this': 'Soup', 'that': 'Sandwich'},
  {'this': 'Homemade Cookies', 'that': 'Store-Bought Cookies'},
  {'this': 'Cake', 'that': 'Pie'},
  {'this': 'Dark Chocolate', 'that': 'White Chocolate'},
  {'this': 'Hot Dog', 'that': 'Corn Dog'},
  {'this': 'Spaghetti', 'that': 'Lasagna'},
  {'this': 'Hamburger', 'that': 'Taco'},
  {'this': 'Fruit Salad', 'that': 'Vegetable Stir-Fry'},
  {'this': 'Rainbow Sprinkles', 'that': 'Chocolate Chips'},
  {'this': 'Ketchup', 'that': 'Mayo'},
  {'this': 'Toast', 'that': 'Eggs'},
  {'this': "Farmer's Market", 'that': 'Supermarket'},
  {'this': 'Smoothie', 'that': 'Milkshake'},
  {'this': 'Steak', 'that': 'Sushi'},
  {'this': 'Hard Shell Taco', 'that': 'Soft-Shell Taco'},
  {'this': 'Dine In', 'that': 'Delivery'},
  {'this': 'Meat', 'that': 'Vegetables'},
  {'this': 'Bakery', 'that': 'Butcher'},
  {'this': 'Pancakes', 'that': 'Waffles'},
  {'this': 'Homemade Bread', 'that': 'Bakery Bread'},
  {'this': 'Ice Cream Cone', 'that': 'Snow Cone'},
  {'this': 'Candy', 'that': 'Popcorn'},
  {'this': 'Microwave', 'that': 'Oven'},
  {'this': 'Fine Dining', 'that': 'Fast Food'},
  {'this': 'Picnic in the Park', 'that': 'Rooftop Dinner'},
  {'this': 'High Tea', 'that': 'Casual Brunch'},
  {'this': 'International Cuisine', 'that': 'National Cuisine'},
  {'this': 'Moon Pies', 'that': 'Zebra Cakes'},
  {
    'this': 'Fancy Restaurant Mediocre Food',
    'that': 'Delicious Food Rough Restaurant'
  },
  {'this': 'Crunchy', 'that': 'Chewy'},
  {'this': 'Presentation', 'that': 'Quantity'},
  {'this': 'Sweet BBQ', 'that': 'Savory BBQ'},
  {'this': 'Thai', 'that': 'Italian'},
  {'this': 'Small Menu', 'that': 'Big Menu'}
];

final List<Map<String, String>> funnyQuestions = [
  {'this': 'Pigeon Chess Tournament', 'that': 'Squirrel Checkers Game'},
  {'this': 'Cheeseburger Hat', 'that': 'Hot Dog Shoes'},
  {
    'this': 'Synchronized Swimming on Land',
    'that': 'Soccer in the Swimming Pool'
  },
  {'this': 'Moustache on a Cat', 'that': 'Sunglasses on a Dog'},
  {'this': 'Blindfolded Cake Baking', 'that': 'Blindfolded Salad Making'},
  {'this': 'Marshmallow Fight', 'that': 'Meatball Fight'},
  {'this': 'Toga Party', 'that': 'Ugly Sweater Party'},
  {'this': 'Belly Flop', 'that': 'Cannonball'},
  {'this': 'Underwater Basket Weaving', 'that': 'Skydiving Knitting'},
  {'this': 'Slippery Banana Peel Ballet', 'that': 'Roller Skate Tango'},
  {'this': 'Square-Dancing Flamingos', 'that': 'Breakdancing Octopuses'},
  {'this': 'Pillow Fortress', 'that': 'Blanket Maze'},
  {'this': 'Bubble-Wrap Popping Contest', 'that': 'Yodeling Contest'},
  {'this': 'Time Traveling Picnic', 'that': 'Space Travel BBQ'},
  {'this': 'Butter Massage', 'that': 'Tomato Soup Bath'},
  {'this': 'Werewolf', 'that': 'Were-Chicken'},
  {'this': 'Marshmallow Boxing', 'that': 'Jelly Wrestling'},
  {'this': 'Hula Hoops', 'that': 'Jump Ropes'},
  {'this': 'Juggling', 'that': 'Unicycling'},
  {'this': 'Llama Parade', 'that': 'Penguin Party'},
  {'this': 'Yawn', 'that': 'Hiccup'},
  {'this': 'Toothpaste Cake', 'that': 'Mouthwash Pie'},
  {'this': 'Meet Aliens', 'that': 'Develop Robots'},
  {'this': 'Zombies', 'that': 'Vampires'},
  {'this': 'Bathrobe Fashion Show', 'that': 'Pajama Red Carpet'},
  {'this': 'Invisible Cats', 'that': 'Rainbow-Colored Glowing Dogs'},
  {'this': 'Spaghetti Tree', 'that': 'Meatball Bush'},
  {'this': 'Time Travel Twice', 'that': 'Teleport Infinite Times'},
  {'this': 'Fly Swatter Fencing', 'that': 'Dustpan Curling'},
  {'this': 'Skiing on Water', 'that': 'Skiing on a Sand Dune'},
  {'this': 'Popcorn Rain', 'that': 'Candy Hail'},
  {'this': 'Yodeling', 'that': 'Beatboxing'},
  {'this': 'Selfie With a Ghost', 'that': 'Photo Bombing Bigfoot'},
  {'this': 'Pickle-Flavored Ice Cream', 'that': 'Bacon-Scented Candles'},
  {'this': 'Lava Lamp', 'that': 'Disco Ball'},
  {'this': 'Snowball Fight', 'that': 'Water Balloon Fight'},
  {'this': 'Rubber Ducks', 'that': 'Rubber Chickens'},
  {'this': 'Alphabet Soup Spelling Bee', 'that': 'Tic-Tac-Toe with Croutons'},
  {'this': 'Disco Ball', 'that': 'Lava Lamp'},
  {'this': 'Werewolves', 'that': 'Mummies'}
];


final List<Map<String, String>> deepQuestions = [
  {'this': 'Free Will', 'that': 'Destiny'},
  {'this': 'Humanity: Inherently Good', 'that': 'Humanity: Inherently Evil'},
  {'this': 'Nature', 'that': 'Nurture'},
  {'this': 'Plan Ahead', 'that': 'Live in the Moment'},
  {'this': 'Ask for Permission', 'that': 'Ask for Forgiveness'},
  {'this': 'God', 'that': 'No God'},
  {
    'this': 'Pursuit of Individual Happiness',
    'that': 'Personal Sacrifice for Betterment of Society'
  },
  {'this': 'Heart', 'that': 'Mind'},
  {'this': 'No Negative Emotions', 'that': 'Full Range of Emotions'},
  {'this': 'Physical Health', 'that': 'Mental Health'},
  {'this': 'Work', 'that': 'Family'},
  {'this': 'Freedom', 'that': 'Safety'},
  {'this': 'Comfort', 'that': 'Effort'},
  {'this': 'Settle', 'that': 'Search'},
  {'this': 'Fit In', 'that': 'Stand Out'},
  {'this': 'Friends', 'that': 'Extended Family'},
  {'this': 'Help Yourself', 'that': 'Help Others'},
  {'this': 'Jack of all Trades', 'that': 'Specialist'},
  {'this': 'Education', 'that': 'Life Experience'},
  {'this': 'Take Advice', 'that': 'Ignore Advice'}
];
